export interface ToolDefinition {
  id: string;
  name: string;
  description: string;
  category: 'images' | 'documents' | 'developer' | 'text' | 'utilities';
  route: string;
  status: 'active' | 'partial' | 'planned' | 'deprecated' | 'alias' | 'internal';
  indexable: boolean;
  capabilities: string[];
  searchIntents: string[];
  relatedTools: string[];
  featured: boolean;
}

export const TOOL_REGISTRY: ToolDefinition[] = [
  {
    id: 'client-side-private-image-compressor',
    name: 'Client-Side Private Image Compressor',
    description: 'Compress PNG, JPEG, WebP and AVIF images locally in browser memory using WebAssembly.',
    category: 'images',
    route: '/client-side-private-image-compressor',
    status: 'active',
    indexable: true,
    capabilities: ['compression', 'wasm', 'batch'],
    searchIntents: ['compress image offline', 'private image compressor', 'wasm jpeg compressor'],
    relatedTools: ['bulk-image-compressor-offline', 'compress-png-images-online', 'compress-image-to-exact-size-kb', 'convert-heic-to-jpg-locally'],
    featured: true
  },
  {
    id: 'convert-heic-to-jpg-locally',
    name: 'Convert HEIC to JPG Locally',
    description: 'Decode iPhone HEIC and HEIF photos locally in browser memory and convert them to standard JPEG.',
    category: 'images',
    route: '/convert-heic-to-jpg-locally',
    status: 'active',
    indexable: true,
    capabilities: ['conversion', 'heic', 'batch'],
    searchIntents: ['convert heic to jpg', 'heic viewer offline', 'apple heic converter'],
    relatedTools: ['client-side-private-image-compressor', 'bulk-image-compressor-offline', 'compress-image-to-exact-size-kb', 'convert-image-to-pdf'],
    featured: true
  },
  {
    id: 'strip-exif-metadata-online-private',
    name: 'Strip EXIF Metadata Privately',
    description: 'Remove sensitive GPS coordinates, camera models, and timestamps from image files locally.',
    category: 'images',
    route: '/strip-exif-metadata-online-private',
    status: 'active',
    indexable: true,
    capabilities: ['privacy', 'metadata', 'exif'],
    searchIntents: ['remove exif metadata', 'strip image location online', 'privacy metadata cleaner'],
    relatedTools: ['blur-sensitive-image-privacy-pixelator', 'client-side-private-image-compressor', 'dpi-ppi-converter-change-image-resolution', 'convert-heic-to-jpg-locally'],
    featured: true
  },
  {
    id: 'bulk-image-compressor-offline',
    name: 'Bulk Local Image Compressor',
    description: 'Compress and optimize dozens or hundreds of images simultaneously in browser memory.',
    category: 'images',
    route: '/bulk-image-compressor-offline',
    status: 'active',
    indexable: true,
    capabilities: ['batch', 'compression', 'zip'],
    searchIntents: ['bulk image compressor', 'batch resize images offline', 'multiple image optimizer'],
    relatedTools: ['client-side-private-image-compressor', 'compress-image-to-exact-size-kb', 'compress-png-images-online', 'convert-image-to-pdf'],
    featured: true
  },
  {
    id: 'compress-png-images-online',
    name: 'Lossless WebAssembly PNG Compressor',
    description: 'Optimize PNG files with advanced WebAssembly quantizers for maximum size reduction.',
    category: 'images',
    route: '/compress-png-images-online',
    status: 'active',
    indexable: true,
    capabilities: ['compression', 'png', 'wasm'],
    searchIntents: ['compress png lossless', 'png quantizer online', 'shrink png size'],
    relatedTools: ['convert-png-to-webp-lossless', 'convert-webp-to-png-transparent', 'client-side-private-image-compressor', 'convert-png-to-jpg-white-background'],
    featured: false
  },
  {
    id: 'convert-webp-to-png-transparent',
    name: 'Convert WebP to PNG (Alpha Intact)',
    description: 'Convert WebP images to standard PNG format while preserving alpha channel transparency.',
    category: 'images',
    route: '/convert-webp-to-png-transparent',
    status: 'active',
    indexable: true,
    capabilities: ['conversion', 'webp', 'png'],
    searchIntents: ['convert webp to png', 'transparent webp converter'],
    relatedTools: ['convert-png-to-webp-lossless', 'compress-png-images-online', 'convert-jpg-to-webp-browser', 'client-side-private-image-compressor'],
    featured: false
  },
  {
    id: 'convert-avif-to-jpg-converter',
    name: 'Convert AVIF to JPG Converter',
    description: 'Decode AVIF image files and convert them to widely compatible JPEG format locally.',
    category: 'images',
    route: '/convert-avif-to-jpg-converter',
    status: 'active',
    indexable: true,
    capabilities: ['conversion', 'avif', 'jpg'],
    searchIntents: ['convert avif to jpg', 'avif decoder online'],
    relatedTools: ['convert-to-avif-online-free', 'convert-heic-to-jpg-locally', 'client-side-private-image-compressor', 'convert-jpg-to-webp-browser'],
    featured: false
  },
  {
    id: 'convert-svg-to-png-transparent',
    name: 'Convert SVG to High-Res PNG',
    description: 'Rasterize vector SVG files into high-resolution PNG images with transparent backgrounds.',
    category: 'images',
    route: '/convert-svg-to-png-transparent',
    status: 'active',
    indexable: true,
    capabilities: ['conversion', 'svg', 'rasterize'],
    searchIntents: ['convert svg to png', 'vector to raster online'],
    relatedTools: ['convert-png-to-webp-lossless', 'client-side-image-to-base64', 'compress-png-images-online'],
    featured: false
  },
  {
    id: 'convert-png-to-webp-lossless',
    name: 'Convert PNG to Lossless WebP',
    description: 'Convert heavy PNG graphics into modern WebP format with lossless compression.',
    category: 'images',
    route: '/convert-png-to-webp-lossless',
    status: 'active',
    indexable: true,
    capabilities: ['conversion', 'png', 'webp'],
    searchIntents: ['convert png to webp', 'lossless webp encoder'],
    relatedTools: ['convert-webp-to-png-transparent', 'compress-png-images-online', 'convert-jpg-to-webp-browser', 'client-side-private-image-compressor'],
    featured: false
  },
  {
    id: 'crop-image-to-exact-aspect-ratio',
    name: 'Crop Image to Custom Aspect Ratio',
    description: 'Crop images precisely to square, 16:9, 4:3, or custom dimensions client-side.',
    category: 'images',
    route: '/crop-image-to-exact-aspect-ratio',
    status: 'active',
    indexable: true,
    capabilities: ['crop', 'editing', 'resize'],
    searchIntents: ['crop image aspect ratio', 'square photo cropper online'],
    relatedTools: ['dpi-ppi-converter-change-image-resolution', 'add-text-watermark-image-browser', 'blur-sensitive-image-privacy-pixelator', 'client-side-private-image-compressor'],
    featured: false
  },
  {
    id: 'add-text-watermark-image-browser',
    name: 'Apply Text Watermark Client-Side',
    description: 'Overlay custom text watermarks onto your image files securely in browser memory.',
    category: 'images',
    route: '/add-text-watermark-image-browser',
    status: 'active',
    indexable: true,
    capabilities: ['watermark', 'editing', 'security'],
    searchIntents: ['add text watermark to image', 'watermark photos offline'],
    relatedTools: ['blur-sensitive-image-privacy-pixelator', 'crop-image-to-exact-aspect-ratio', 'strip-exif-metadata-online-private', 'client-side-private-image-compressor'],
    featured: false
  },
  {
    id: 'convert-tiff-bmp-to-jpg',
    name: 'Convert TIFF & BMP to JPG',
    description: 'Convert legacy TIFF and BMP raster images into standard JPEG format.',
    category: 'images',
    route: '/convert-tiff-bmp-to-jpg',
    status: 'active',
    indexable: true,
    capabilities: ['conversion', 'tiff', 'bmp'],
    searchIntents: ['convert tiff to jpg', 'bmp converter online'],
    relatedTools: ['convert-heic-to-jpg-locally', 'convert-png-to-jpg-white-background', 'client-side-private-image-compressor'],
    featured: false
  },
  {
    id: 'dpi-ppi-converter-change-image-resolution',
    name: 'Change Image DPI & PPI for Print',
    description: 'Adjust image resolution metadata (DPI/PPI) for printing and document submission.',
    category: 'images',
    route: '/dpi-ppi-converter-change-image-resolution',
    status: 'active',
    indexable: true,
    capabilities: ['resolution', 'dpi', 'print'],
    searchIntents: ['change image dpi online', 'ppi resizer tool'],
    relatedTools: ['crop-image-to-exact-aspect-ratio', 'convert-image-to-pdf', 'client-side-private-image-compressor'],
    featured: false
  },
  {
    id: 'convert-jpg-to-webp-browser',
    name: 'Convert JPG to WebP in Browser',
    description: 'Convert standard JPEG photos to high-compression WebP format.',
    category: 'images',
    route: '/convert-jpg-to-webp-browser',
    status: 'active',
    indexable: true,
    capabilities: ['conversion', 'jpg', 'webp'],
    searchIntents: ['convert jpg to webp', 'jpeg to webp converter'],
    relatedTools: ['convert-png-to-webp-lossless', 'convert-webp-to-png-transparent', 'client-side-private-image-compressor'],
    featured: false
  },
  {
    id: 'compress-image-to-exact-size-kb',
    name: 'Exact Size Image Compressor (KB)',
    description: 'Compress images precisely to target file sizes in kilobytes (e.g. 50KB, 100KB, 200KB).',
    category: 'images',
    route: '/compress-image-to-exact-size-kb',
    status: 'active',
    indexable: true,
    capabilities: ['compression', 'target-size', 'kb'],
    searchIntents: ['compress image to kb', 'shrink photo to 100kb', 'image size reducer kb'],
    relatedTools: ['client-side-private-image-compressor', 'bulk-image-compressor-offline', 'compress-png-images-online'],
    featured: true
  },
  {
    id: 'convert-ico-to-png-favicon-extractor',
    name: 'Extract ICO Favicon to PNG',
    description: 'Extract multi-resolution ICO icon files into individual transparent PNG images.',
    category: 'images',
    route: '/convert-ico-to-png-favicon-extractor',
    status: 'active',
    indexable: true,
    capabilities: ['conversion', 'ico', 'favicon'],
    searchIntents: ['convert ico to png', 'extract favicon online'],
    relatedTools: ['convert-png-to-webp-lossless', 'client-side-image-to-base64', 'convert-svg-to-png-transparent'],
    featured: false
  },
  {
    id: 'convert-png-to-jpg-white-background',
    name: 'Convert PNG to JPG (White Fill)',
    description: 'Flatten transparent PNG images onto a clean white background and convert to JPEG.',
    category: 'images',
    route: '/convert-png-to-jpg-white-background',
    status: 'active',
    indexable: true,
    capabilities: ['conversion', 'png', 'jpg', 'flatten'],
    searchIntents: ['convert png to jpg white background', 'remove transparency jpeg'],
    relatedTools: ['convert-webp-to-png-transparent', 'compress-png-images-online', 'client-side-private-image-compressor'],
    featured: false
  },
  {
    id: 'blur-sensitive-image-privacy-pixelator',
    name: 'Blur & Pixelate Sensitive Info',
    description: 'Obscure sensitive text, faces, or personal data on images locally before sharing.',
    category: 'images',
    route: '/blur-sensitive-image-privacy-pixelator',
    status: 'active',
    indexable: true,
    capabilities: ['privacy', 'blur', 'pixelate'],
    searchIntents: ['blur sensitive image data', 'pixelate face online private'],
    relatedTools: ['strip-exif-metadata-online-private', 'add-text-watermark-image-browser', 'client-side-private-image-compressor'],
    featured: false
  },
  {
    id: 'convert-to-avif-online-free',
    name: 'Convert Images to AVIF Format',
    description: 'Encode JPEG and PNG images into modern AVIF format with superior compression.',
    category: 'images',
    route: '/convert-to-avif-online-free',
    status: 'active',
    indexable: true,
    capabilities: ['conversion', 'avif', 'compression'],
    searchIntents: ['convert to avif online', 'image to avif encoder'],
    relatedTools: ['convert-avif-to-jpg-converter', 'convert-png-to-webp-lossless', 'client-side-private-image-compressor'],
    featured: false
  },
  {
    id: 'convert-image-to-pdf',
    name: 'Convert Images to PDF',
    description: 'Combine multiple JPG, PNG, or HEIC images into a single multi-page PDF document locally.',
    category: 'documents',
    route: '/convert-image-to-pdf',
    status: 'active',
    indexable: true,
    capabilities: ['pdf', 'conversion', 'images', 'merge'],
    searchIntents: ['jpg to pdf', 'image to pdf converter', 'combine images to pdf', 'png to pdf offline'],
    relatedTools: ['merge-pdf', 'convert-pdf-pages-to-jpg-images', 'secure-document-compressor-pdf', 'client-side-private-image-compressor'],
    featured: true
  },
  {
    id: 'merge-pdf',
    name: 'Merge PDF Files Online',
    description: 'Combine multiple PDF documents into a single file securely in your browser with zero server uploads.',
    category: 'documents',
    route: '/merge-pdf',
    status: 'active',
    indexable: true,
    capabilities: ['pdf', 'merge', 'offline'],
    searchIntents: ['merge pdf files online', 'combine pdfs offline', 'join pdf documents free'],
    relatedTools: ['split-pdf', 'convert-pdf-pages-to-jpg-images', 'secure-document-compressor-pdf', 'compress-image-to-exact-size-kb', 'client-side-private-image-compressor'],
    featured: true
  },
  {
    id: 'split-pdf',
    name: 'Split PDF Pages Online Free',
    description: 'Extract specific pages or page ranges from PDF files instantly in your browser.',
    category: 'documents',
    route: '/split-pdf',
    status: 'active',
    indexable: true,
    capabilities: ['pdf', 'split', 'extraction'],
    searchIntents: ['split pdf pages online', 'extract pdf pages offline', 'pdf page separator'],
    relatedTools: ['merge-pdf', 'convert-pdf-pages-to-jpg-images', 'secure-document-compressor-pdf', 'compress-image-to-exact-size-kb', 'client-side-private-image-compressor'],
    featured: true
  },
  {
    id: 'convert-pdf-pages-to-jpg-images',
    name: 'Extract PDF Pages to JPG Images',
    description: 'Render PDF document pages into high-resolution JPG images locally in browser memory.',
    category: 'documents',
    route: '/convert-pdf-pages-to-jpg-images',
    status: 'active',
    indexable: true,
    capabilities: ['pdf', 'conversion', 'extraction'],
    searchIntents: ['convert pdf pages to jpg', 'extract images from pdf offline'],
    relatedTools: ['merge-pdf', 'split-pdf', 'compress-image-to-exact-size-kb', 'client-side-private-image-compressor'],
    featured: true
  },
  {
    id: 'secure-document-compressor-pdf',
    name: 'Secure Document Compressor (PDF)',
    description: 'Optimize PDF files locally in your browser with privacy guarantees.',
    category: 'documents',
    route: '/secure-document-compressor-pdf',
    status: 'active',
    indexable: true,
    capabilities: ['pdf', 'compression', 'security'],
    searchIntents: ['compress pdf offline', 'secure document compressor'],
    relatedTools: ['merge-pdf', 'split-pdf', 'convert-pdf-pages-to-jpg-images', 'compress-image-to-exact-size-kb', 'client-side-private-image-compressor'],
    featured: true
  },
  {
    id: 'client-side-image-to-base64',
    name: 'Client-Side Image to Base64 Encoder',
    description: 'Encode images into Base64 data URIs instantly for web development and CSS embedding.',
    category: 'developer',
    route: '/client-side-image-to-base64',
    status: 'active',
    indexable: true,
    capabilities: ['developer', 'base64', 'encoding'],
    searchIntents: ['image to base64 converter', 'encode image data uri'],
    relatedTools: ['json-formatter-validator', 'palette-color-extractor-image-hex', 'client-side-private-image-compressor'],
    featured: true
  },
  {
    id: 'palette-color-extractor-image-hex',
    name: 'Image Color Palette Extractor (HEX)',
    description: 'Extract dominant color palettes and HEX codes from any image instantly.',
    category: 'utilities',
    route: '/palette-color-extractor-image-hex',
    status: 'active',
    indexable: true,
    capabilities: ['design', 'colors', 'palette'],
    searchIntents: ['extract color palette from image', 'image color hex picker'],
    relatedTools: ['json-formatter-validator', 'client-side-image-to-base64', 'client-side-private-image-compressor'],
    featured: false
  },
  {
    id: 'json-formatter-validator',
    name: 'JSON Formatter & Validator',
    description: 'Format, beautify, minify, and validate JSON data locally in browser memory with detailed syntax diagnostics.',
    category: 'developer',
    route: '/json-formatter-validator',
    status: 'active',
    indexable: true,
    capabilities: ['developer', 'json', 'formatter', 'validator', 'tree-view', 'minify'],
    searchIntents: ['json formatter', 'json validator online', 'beautify json offline', 'format json private', 'json tree viewer'],
    relatedTools: ['regex-tester', 'jwt-decoder', 'csv-to-json-converter', 'client-side-image-to-base64'],
    featured: true
  },
  {
    id: 'csv-to-json-converter',
    name: 'CSV ↔ JSON Converter',
    description: 'Convert CSV/TSV spreadsheets to JSON arrays or transform JSON objects to RFC 4180 CSV tables locally in browser memory.',
    category: 'developer',
    route: '/csv-to-json-converter',
    status: 'active',
    indexable: true,
    capabilities: ['developer', 'csv', 'json', 'converter', 'tsv', 'table-view'],
    searchIntents: ['csv to json', 'json to csv', 'convert csv to json offline', 'csv json converter private', 'tsv to json'],
    relatedTools: ['regex-tester', 'json-formatter-validator', 'jwt-decoder', 'client-side-image-to-base64'],
    featured: true
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Debugger & Decoder',
    description: 'Decode, inspect, and verify JSON Web Tokens (JWT) locally with real-time expiration countdown and client-side signature verification.',
    category: 'developer',
    route: '/jwt-decoder',
    status: 'active',
    indexable: true,
    capabilities: ['developer', 'jwt', 'decoder', 'debugger', 'security', 'auth'],
    searchIntents: ['jwt decoder', 'decode jwt online', 'jwt debugger offline', 'jwt token viewer', 'jwt inspector', 'verify jwt signature client-side'],
    relatedTools: ['regex-tester', 'json-formatter-validator', 'csv-to-json-converter', 'client-side-image-to-base64'],
    featured: true
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester & String Debugger',
    description: 'Test, debug, and analyze regular expressions locally with real-time match highlighting, capture group inspection, Unicode string diagnostics, and replacement preview.',
    category: 'developer',
    route: '/regex-tester',
    status: 'active',
    indexable: true,
    capabilities: ['developer', 'regex', 'tester', 'debugger', 'string-diagnostics', 'replace', 'unicode'],
    searchIntents: ['regex tester', 'regular expression tester', 'regex debugger', 'regex match tester', 'test regex online', 'javascript regex tester'],
    relatedTools: ['markdown-live-preview', 'json-formatter-validator', 'jwt-decoder', 'csv-to-json-converter'],
    featured: true
  },
  {
    id: 'markdown-live-preview',
    name: 'Markdown Live Previewer & Converter',
    description: 'Edit, preview, and convert GitHub-Flavored Markdown (GFM) in real-time with table alignments, task lists, code blocks, XSS sanitization, and offline exports.',
    category: 'text',
    route: '/markdown-live-preview',
    status: 'active',
    indexable: true,
    capabilities: ['text', 'markdown', 'gfm', 'previewer', 'converter', 'html-export', 'sanitizer', 'unicode'],
    searchIntents: ['markdown live preview', 'gfm editor online', 'markdown to html converter', 'markdown editor private', 'markdown preview offline'],
    relatedTools: ['text-diff', 'regex-tester', 'json-formatter-validator', 'jwt-decoder'],
    featured: true
  },
  {
    id: 'text-diff',
    name: 'Diff Viewer & Text Comparator',
    description: 'Compare two text or code files side-by-side or in unified view with character-level diff highlighting, whitespace controls, statistics, and offline patch export.',
    category: 'text',
    route: '/text-diff',
    status: 'active',
    indexable: true,
    capabilities: ['text', 'diff', 'comparison', 'side-by-side', 'unified', 'patch', 'unicode'],
    searchIntents: ['text diff', 'diff viewer online', 'compare text side by side', 'code diff checker', 'diff comparator offline', 'unified diff viewer'],
    relatedTools: ['markdown-live-preview', 'regex-tester', 'json-formatter-validator', 'csv-to-json-converter'],
    featured: true
  }
];
