import { TargetFormat } from '../../types';

export interface SeoRouteItem {
  path: string;
  label: string;
  category: 'converter' | 'compression' | 'use-case' | 'resource';
}

export const DOMAIN = 'https://zapixal.com';

export const PSEO_ROUTES_LIST: SeoRouteItem[] = [
  // High-Conversion Long-Tail Routes
  { path: '/discord-profile-picture-compressor', label: 'Discord PFP Compressor (Under 8MB)', category: 'use-case' },
  { path: '/iphone-photo-to-jpeg-for-email', label: 'Convert iPhone HEIC to JPEG for Email', category: 'use-case' },
  { path: '/compress-image-under-100kb-for-government-form', label: 'Compress Image Under 100KB for Gov Forms', category: 'use-case' },
  { path: '/passport-application-photo-compressor', label: 'Passport Application Photo Compressor', category: 'use-case' },
  { path: '/heic-to-jpg-batch-converter-for-windows', label: 'Batch HEIC to JPG Converter for Windows', category: 'converter' },
  { path: '/shopify-product-photo-compressor', label: 'Shopify Product Photo Compressor', category: 'use-case' },
  { path: '/remove-exif-data-for-reddit', label: 'Remove EXIF Data for Reddit', category: 'use-case' },
  { path: '/compress-images-for-amazon-listings', label: 'Compress Images for Amazon Listings', category: 'use-case' },
  { path: '/etsy-product-photo-optimizer', label: 'Etsy Product Photo Optimizer', category: 'use-case' },
  { path: '/convert-heic-to-jpg-for-upload', label: 'Convert HEIC to JPG for Online Upload', category: 'converter' },

  // Educational Authority Clusters
  { path: '/jpeg-vs-png', label: 'JPEG vs PNG Guide', category: 'resource' },
  { path: '/heic-explained', label: 'HEIC Explained', category: 'resource' },
  { path: '/webp-explained', label: 'WebP Explained', category: 'resource' },
  { path: '/avif-explained', label: 'AVIF Explained', category: 'resource' },
  { path: '/how-image-compression-works', label: 'How Image Compression Works', category: 'resource' },
  { path: '/what-is-exif', label: 'What Is EXIF', category: 'resource' },
  { path: '/image-dpi-guide', label: 'Image DPI Guide', category: 'resource' },
  { path: '/color-profiles-explained', label: 'Color Profiles Explained', category: 'resource' },
  { path: '/rgb-vs-cmyk', label: 'RGB vs CMYK', category: 'resource' },
  { path: '/image-dimensions-guide', label: 'Image Dimensions Guide', category: 'resource' },
  { path: '/social-media-image-size-guide', label: 'Social Media Image Size Guide', category: 'resource' },
  { path: '/government-image-upload-requirements', label: 'Government Image Upload Requirements', category: 'resource' },

  // Programmatic Matrices
  { path: '/resize-image-to-1920x1080', label: 'Resize Image to 1920x1080', category: 'use-case' },
  { path: '/bulk-compress-500-images', label: 'Bulk Compress 500 Images', category: 'compression' },
  { path: '/lossless-png-compressor', label: 'Lossless PNG Compressor', category: 'compression' },
  { path: '/low-memory-web-image-compressor', label: 'Low-Memory Image Compressor', category: 'use-case' },
  { path: '/image-compressor-for-tax-portal', label: 'Image Compressor for Tax Portal', category: 'use-case' },
  { path: '/real-estate-photography-compressor', label: 'Real Estate Photography Compressor', category: 'use-case' },
  { path: '/compress-jpeg-without-losing-quality', label: 'Compress JPEG Without Losing Quality', category: 'compression' },
  { path: '/compress-transparent-png-without-losing-quality', label: 'Compress Transparent PNG Without Losing Quality', category: 'compression' },
  { path: '/compress-animated-gif-without-losing-quality', label: 'Compress Animated GIF Without Losing Quality', category: 'compression' },

  // Standard Routes
  { path: '/heic-to-jpg', label: 'HEIC to JPG Converter', category: 'converter' },
  { path: '/webp-to-png', label: 'WEBP to PNG Converter', category: 'converter' },
  { path: '/compress-image', label: 'Compress Image Size', category: 'compression' },
  { path: '/strip-exif', label: 'Strip EXIF Metadata', category: 'use-case' },
  { path: '/convert-png-to-webp', label: 'PNG to WEBP Converter', category: 'converter' },
  { path: '/convert-webp-to-jpg', label: 'WEBP to JPG Converter', category: 'converter' },
  { path: '/convert-png-to-avif', label: 'PNG to AVIF Converter', category: 'converter' },
  { path: '/convert-jpg-to-ico', label: 'JPG to ICO Favicon', category: 'converter' },
  { path: '/convert-heic-to-png', label: 'HEIC to PNG Converter', category: 'converter' },
  { path: '/compress-jpeg-under-200kb', label: 'Compress JPEG Under 200KB', category: 'compression' },
  { path: '/compress-jpeg-under-100kb', label: 'Compress JPEG Under 100KB', category: 'compression' },
  { path: '/compress-png-under-500kb', label: 'Compress PNG Under 500KB', category: 'compression' },
  { path: '/compress-image-under-50kb', label: 'Compress Image Under 50KB', category: 'compression' },
  { path: '/compress-jpeg-under-500kb', label: 'Compress JPEG Under 500KB', category: 'compression' },
  { path: '/passport-photo-compressor', label: 'Passport Photo Compressor', category: 'use-case' },
  { path: '/exif-metadata-remover', label: 'EXIF Metadata Remover', category: 'use-case' },
  { path: '/shopify-product-image-optimizer', label: 'Shopify Image Optimizer', category: 'use-case' },
  { path: '/real-estate-photo-compressor', label: 'Real Estate Photo Compressor', category: 'use-case' },
  { path: '/youtube-thumbnail-compressor', label: 'YouTube Thumbnail Compressor', category: 'use-case' },
  { path: '/website-image-optimizer', label: 'Website Image Optimizer', category: 'use-case' },
  { path: '/iphone-photo-converter', label: 'iPhone Photo Converter', category: 'use-case' },
  { path: '/reduce-image-size', label: 'Reduce Image Size', category: 'compression' },
  { path: '/image-resizer-online', label: 'Image Resizer Online', category: 'converter' },
  { path: '/calculator', label: 'Image Cost Calculator', category: 'resource' },
  { path: '/privacy-map', label: 'Privacy Visualizer', category: 'resource' },
  { path: '/docs/architecture', label: 'Technical Architecture', category: 'resource' },
  { path: '/vs/cloudconvert', label: 'Zapixal vs CloudConvert', category: 'resource' },
  { path: '/vs/tinypng', label: 'Zapixal vs TinyPNG', category: 'resource' },
  { path: '/vs/iloveimg', label: 'Zapixal vs iLoveIMG', category: 'resource' },
  { path: '/vs/squoosh', label: 'Zapixal vs Squoosh', category: 'resource' },
  { path: '/vs/freeconvert', label: 'Zapixal vs FreeConvert', category: 'resource' },
  { path: '/vs/compressjpeg', label: 'Zapixal vs CompressJPEG', category: 'resource' },
  { path: '/convert/heic-to-jpg-offline', label: 'Convert HEIC to JPG Offline', category: 'converter' },
  { path: '/compress/image-under-100kb', label: 'Compress Image Under 100KB', category: 'compression' },
  { path: '/convert/webp-to-png', label: 'WebP to PNG Converter', category: 'converter' },
  { path: '/convert/batch-heic-to-jpg-mac', label: 'Batch HEIC to JPG for Mac', category: 'converter' },
  { path: '/compress/reduce-image-size-in-kb-offline', label: 'Reduce Image Size in KB Offline', category: 'compression' },
  { path: '/convert/png-to-avif-client-side', label: 'PNG to AVIF Client-Side', category: 'converter' },
  { path: '/security/no-upload-image-converter', label: 'No-Upload Image Converter', category: 'resource' },
  { path: '/compress/discord-pfp-compressor-under-8mb', label: 'Discord PFP Compressor (Under 8MB)', category: 'compression' },
  { path: '/compress/image-to-50kb-for-form', label: 'Compress Image to 50KB for Forms', category: 'compression' },
  { path: '/compress-image-to-20kb', label: 'Compress Image to 20KB', category: 'compression' },
  { path: '/compress-image-to-50kb', label: 'Compress Image to 50KB', category: 'compression' },
  { path: '/compress-image-to-100kb', label: 'Compress Image to 100KB', category: 'compression' },
  { path: '/compress-image-to-200kb', label: 'Compress Image to 200KB', category: 'compression' },
  { path: '/compress-image-to-500kb', label: 'Compress Image to 500KB', category: 'compression' },
  { path: '/compress-image-under-1mb', label: 'Compress Image Under 1MB', category: 'compression' },
  { path: '/compress-image-under-2mb', label: 'Compress Image Under 2MB', category: 'compression' },
  { path: '/convert-heic-to-jpg-windows', label: 'Convert HEIC to JPG Windows', category: 'converter' },
  { path: '/convert-heic-to-jpg-mac', label: 'Convert HEIC to JPG Mac', category: 'converter' },
  { path: '/convert-avif-to-png', label: 'AVIF to PNG Converter', category: 'converter' },
  { path: '/convert-png-to-ico', label: 'PNG to ICO Favicon', category: 'converter' },
  { path: '/discord-emoji-compressor', label: 'Discord Emoji Compressor', category: 'use-case' },
  { path: '/whatsapp-status-compressor', label: 'WhatsApp Status Compressor', category: 'use-case' },
  { path: '/instagram-story-compressor', label: 'Instagram Story Compressor', category: 'use-case' },
  { path: '/twitter-header-compressor', label: 'Twitter Header Compressor', category: 'use-case' },
  { path: '/remove-gps-from-photo-offline', label: 'Remove GPS from Photo', category: 'use-case' },
  { path: '/secure-image-converter-no-upload', label: 'Secure No-Upload Converter', category: 'resource' },
  { path: '/offline-batch-image-resizer', label: 'Offline Batch Image Resizer', category: 'use-case' },
  { path: '/passport-photo-compressor-50kb', label: 'Passport Photo under 50KB', category: 'use-case' },
  { path: '/convert-jpg-to-png', label: 'JPG to PNG Converter', category: 'converter' },
  { path: '/convert-png-to-jpg', label: 'PNG to JPG Converter', category: 'converter' },
  { path: '/convert-avif-to-webp', label: 'AVIF to WEBP Converter', category: 'converter' },
  { path: '/convert-webp-to-avif', label: 'WEBP to AVIF Converter', category: 'converter' },
  { path: '/convert-svg-to-png', label: 'SVG to PNG Converter', category: 'converter' },
  { path: '/convert-bmp-to-jpg', label: 'BMP to JPG Converter', category: 'converter' },
  { path: '/convert-tiff-to-jpg', label: 'TIFF to JPG Converter', category: 'converter' },
  { path: '/convert-heic-to-pdf', label: 'HEIC to PDF Converter', category: 'converter' },
  { path: '/convert-jpg-to-pdf', label: 'JPG to PDF Converter', category: 'converter' },
  { path: '/convert-png-to-pdf', label: 'PNG to PDF Converter', category: 'converter' },
  { path: '/batch-image-compressor', label: 'Batch Image Compressor', category: 'compression' },
  { path: '/compress-jpeg-under-30kb', label: 'Compress JPEG Under 30KB', category: 'compression' },
  { path: '/compress-png-under-100kb', label: 'Compress PNG Under 100KB', category: 'compression' },
  { path: '/compress-png-under-200kb', label: 'Compress PNG Under 200KB', category: 'compression' },
  { path: '/compress-webp-under-100kb', label: 'Compress WEBP Under 100KB', category: 'compression' },
  { path: '/signature-photo-compressor-20kb', label: 'Signature Photo Compressor (20KB)', category: 'use-case' },
  { path: '/etsy-product-photo-compressor', label: 'Etsy Product Photo Optimizer', category: 'use-case' },
  { path: '/ebay-listing-image-compressor', label: 'eBay Listing Image Resizer', category: 'use-case' },
  { path: '/amazon-image-compressor-1000px', label: 'Amazon Product Photo Resizer', category: 'use-case' },
  { path: '/college-application-photo-50kb', label: 'College Form Photo (50KB)', category: 'use-case' },
  { path: '/linkedin-banner-resizer-1584x396', label: 'LinkedIn Banner Resizer', category: 'use-case' },
];
